site_name: NetDaemon - Application daemon written in .NET core.
theme: 'material' #m
# google_analytics:
#   - UA-133997912-1
#   - auto
repo_url: https://github.com/helto4real/netdaemon/
site_dir: site
site_author: 'Tomas Hellstr√∂m, @helto4real'
dev_addr: 127.0.0.1:8001
markdown_extensions:
    - fenced_code
    - codehilite
    - admonition
nav:
    - Home: index.md
    - Getting Started:
        - Getting started/1_getting started.md
        - Getting started/2_basics.md
        - Getting started/3_example app.md

    - API:
        API Start: API/api.md
        Fluent API:
            - Entity selections: API/Fluent/fluent_api_entities.md
            - State changes: API/Fluent/fluent_api_state.md
        Standard API:
            - Get state: API/Standard API/standard_api_get_state.md

    - Licence: license.md