name: Check labels
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
    chech_labels:
        name: ðŸ”¨ Check valid labels
        runs-on: ubuntu-latest
        steps:
            - name: Check valid labels
              uses: jesusvasquez333/verify-pr-label-action@v1.4.0
              with:
                github-token: '${{ secrets.GITHUB_TOKEN }}'
                valid-labels: 'pr:bugfix, pr: enhancement, pr: dependency-update, pr: new feature'
                pull-request-number: '${{ github.event.pull_request.number }}'
