#### Publish tags to docker hub
name: Deploy dev builds of addon
on:
  push:
    branches:
      - dev
      - add_on_build
    paths:
      - 'src/*'
jobs:
  deploy:
    name: Deploy addon (dev)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run deploy script using builder
        run: docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v $(Build.SourcesDirectory)/addon:/data homeassistant/amd64-builder -t /data --all --docker-user $(docker_user) --docker-password $(docker_password)