#### Publish tags to docker hub
name: ğŸ“¦ Push to nuget manual
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Enter version number"
        required: true
        default: "21.43.0"

jobs:
  deploy_nuget:
    name: ğŸ“¦ publish nuget packages manual version
    runs-on: ubuntu-latest
    environment: CI - release environment
    steps:
      - name: ğŸ“¤ Checkout the repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: â­ï¸ Get next version
        id: version
        run: |
          latest=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo Current version:    $latest
          echo "::set-output name=version::$latest"

      - name: ğŸ¥… Install .Net 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x" # SDK Version

      - name: ğŸ”– Set version number
        run: |
          sed -i "/        private const string Version = /c\        private const string Version =  \"${{ github.event.inputs.tag }}\";" ${{github.workspace}}/src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
      - name: ğŸ Pack AppModel
        run: dotnet pack src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj --configuration Release -p:PackageVersion=${{ github.event.inputs.tag }}
      - name: ğŸ Pack HassModel
        run: dotnet pack src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj --configuration Release -p:PackageVersion=${{ github.event.inputs.tag }}
      - name: ğŸ Pack HassModel integration
        run: dotnet pack src/HassModel/NetDaemon.HassModel.Integration/NetDaemon.HassModel.Integration.csproj --configuration Release -p:PackageVersion=${{ github.event.inputs.tag }}
      - name: ğŸ Pack HassModel codegen
        run: dotnet pack src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj --configuration Release -p:PackageVersion=${{ github.event.inputs.tag }}
      - name: ğŸ Pack scheduling extensions
        run: dotnet pack src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj --configuration Release -p:PackageVersion=${{ github.event.inputs.tag }}
      - name: ğŸ Pack logging extensions
        run: dotnet pack src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj --configuration Release -p:PackageVersion=${{ github.event.inputs.tag }}
      - name: ğŸ Pack TTS extensions
        run: dotnet pack src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj --configuration Release -p:PackageVersion=${{ github.event.inputs.tag }}
      - name: ğŸ“¨ Push to nuget
        run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --no-symbols true
