#### Publish tags to docker hub
name: ğŸ‘€ Test docker
on:
  pull_request:
    branches:
      - main
      - dev
      - dotnet8

jobs:
  test:
    name: ğŸ‘€ Test image build ${{ matrix.dockerfile }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - Dockerfile
          - Dockerfile.AddOn
    steps:
      - name: ğŸ“¤ Checkout the repository
        uses: actions/checkout@main
      - name: ğŸ“ Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: ğŸ”§ Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: ğŸ§° Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: ğŸ› ï¸ Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm,linux/arm64,linux/amd64 \
            --output "type=image,push=false" \
            --no-cache \
            --file ./${{ matrix.dockerfile }} . \
            --tag netdaemon/netdaemon4:dev
